# Intro to Numpy

<img src='https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/NumPy_logo.svg/1200px-NumPy_logo.svg.png' width='500px'>

## `Contents`

- <a href="#Introduction"> Introduction </a>
- <a href="#Installation"> Installation </a>
- <a href="#N-dimensional-arrays"> N-dimensional arrays </a>
- <a href="#dtype"> dtype </a>
- <a href="#np.zeros"> np.zeros </a>
- <a href="#np.ones"> np.ones </a>
- <a href="#np.empty"> np.empty </a>
- <a href="#np.full"> np.full </a>
- <a href="#np.arange"> np.arange </a>
- <a href="#np.ones"> np.ones </a>
- <a href="#np.rand"> np.rand </a>
- <a href="#np.randn"> np.randn </a>
- <a href="#np.fromfunction"> np.fromfunction </a>
- <a href="#reshape"> reshape </a>


<br><br>

## `Introduction`

**NumPy is the fundamental library for scientific computing with Python. NumPy is centered around a powerful N-dimensional array object, and it also contains useful linear algebra, Fourier transform, and random number functions.**

## `Installation`

`pip install numpy`

In [1]:
# Let's import numpy as np
import numpy as np

## `N-dimensional arrays`

In [2]:
# Create a python list
py_list = [[1, 2, 3],
            [4, 5, 6],
            [7, 8, 9]]

In [3]:
py_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
type(py_list)

list

In [5]:
# python list to numpy array
np_array = np.array(py_list)

In [6]:
np_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# type
type(np_array)

numpy.ndarray

In [8]:
# shape of the array
np_array.shape

(3, 3)

In [9]:
# dimension of the array
np_array.ndim

2

In [10]:
# size of the array 
np_array.size

9

## dtype 

In [11]:
np_array.dtype

dtype('int32')

In [12]:
new_array = np.array([1., 2.22, 3.4, 4.4], dtype = np.int32)

In [13]:
new_array

array([1, 2, 3, 4])

In [14]:
new_array.dtype

dtype('int32')

## `np.zeros`

`np.zeros` function creates an array containing any number of zeros

In [15]:
# 1d array (victor) of zeros
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [16]:
# 2D array (matrix) of zeros
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
# 3D array (tensor) of zeros
z = np.zeros((3, 5, 7))
z

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [18]:
# shape of array
z.shape

(3, 5, 7)

In [19]:
z.ndim 

3

In [20]:
# size of array
z.size

105

## `np.ones`

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## `np.empty`

In [22]:
np.empty((2,3))

array([[2.67276450e+185, 1.69506143e+190, 1.75184137e+190],
       [9.48819320e+077, 1.63730399e-306, 0.00000000e+000]])

## `np.full`

In [23]:
np.full((3,4), 7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

## `np.arange`

In [24]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(0.0, 10.5)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [26]:
np.arange(1, 10.5, 0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [27]:
np.arange(0, 5/3, 1/3)

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667])

## `np.ones`

In [28]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## `np.rand`

In [29]:
np.random.rand(3,3)

array([[0.98747777, 0.01953884, 0.40537634],
       [0.30472147, 0.09218058, 0.62972471],
       [0.67154418, 0.69192189, 0.06439755]])

## `np.randn`

In [30]:
np.random.randn(3,3)

array([[ 0.45763515, -1.2311684 ,  0.84495857],
       [-0.25122285,  0.72640014, -0.77281061],
       [ 0.53796745, -1.95559131,  0.49454919]])

## `np.fromfunction`

In [31]:
def function(x, y):
    return x ** y

np.fromfunction(function, (2, 3))

array([[1., 0., 0.],
       [1., 1., 1.]])

## `reshape`