# Support Vector Machines
<br>
Support Vector Machine (SVM) is a very powerful and versatile supervised Machine Learning
algorithm. It's able to perform linear & non-linear classification, regression, and even
outlier detection. SVM support kernel trick to maximum-margin hyperplanes.

SVM algorithm was invented by Vladimir N. Vapnik and Alexey Ya. Chervonenkis in 1963

In [10]:
# For python 2 and python 3
from __future__ import division, print_function, unicode_literals

import numpy as np

# To ploting  
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt

# import SVM
from sklearn import svm

## SVM Classification
`sklearn > svm > SVC()`


In [11]:
X = [[0, 0], [1, 1],[2, 2],[3, 3]] # Here our feature
y = [0, 1, 2, 3] # And here our label

# Now let's define our classifier
clf = svm.SVC() # Here our classifier 'sklearn > svm > SVC()' [We keep it default]

# Let's train our classifier by passing feature X and label y using fit()
clf.fit(X, y) 

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

After training our model we can see the default parameters.

**We can change the parameters for different type of data.**
#### The kernel functions:
* linear
* polynomial
* rbf
* sigmoid 


Now we can use our model to make a prediction.

In [12]:
clf.predict([[2., 2.]])

array([2])

In [13]:
#Now let's try to predict label by a unknown data
clf.predict([[2.01, 2.4]])

array([2])

### Awesome! we've just created our very first  Machine Learning model that can predict label of unknown data

To build an SVM classifier we have to follow these step.

## SVM Linear Classifier
`sklearn > svm > LinearSVC()`

In [21]:
X_l = [[0], [1], [2]]
Y_l = [0, 1, 2]
lin_clf = svm.LinearSVC()
lin_clf.fit(X_l, Y_l) 

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [23]:
lin_clf.predict([[2]])

array([2])

# SVM Regression
`sklearn > svm > SVR()`

In [25]:
from sklearn import svm
X = [[0, 0], [2, 2]]
y = [0.5, 2.5]
clf = svm.SVR()
clf.fit(X, y) 


SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma='auto',
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [26]:
clf.predict([[1, 1]])


array([1.5])